### PR TITLE
Use port's name

### PR DESCRIPTION
**Pull request by gbonnefille**
Use the port's name as its value is configurable.

### CODE REVIEW

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @gbonnefille ,

thanks for your contribution and this is a good spotting of a potential error if a user defined sonarqube to be run on a different port. i would happily accept your PR if:
* you bump the chart version 
* do the fix for the sts and the dce as well 
* add your changes to the changelog

if using a named port is not possible (like in the bash script for the readinessProbe), you can use `{{.Values.service.internalPort}}`

**Review by tobias-trabelsi-sonarsource — CHANGES_REQUESTED** [review]
Hi @gbonnefille ,

thanks for your contribution and this is a good spotting of a potential error if a user defined sonarqube to be run on a different port. i would happily accept your PR if:

* you bump the chart version
* do the fix for the sts and the dce as well
* add your changes to the changelog

if using a named port is not possible (like in the bash script for the readinessProbe), you can use `{{.Values.service.internalPort}}`

**Comment by gbonnefille** [comment]
I did all required changes.

**Review by tobias-trabelsi-sonarsource — APPROVED** [review]
LGTM. Thanks :+1:

**Pull request merged**
