### PR TITLE
Update LTS Helm Chart to add missing ENV Header for the install-plugins container

### PR DESCRIPTION
**Pull request by snorlaX-sleeps**
This is required when passing in the env variable in the values file.
While missing this creates various errors when trying to lint or template the Helm chart

Resolves https://github.com/SonarSource/helm-chart-sonarqube/issues/133

Signed-off-by: Adam Robinson <21spock@gmail.com>

### CODE REVIEW

**Review by tobias-trabelsi-sonarsource — CHANGES_REQUESTED** [review]
Good Catch! 
Please increase the chart version and mention your changes in the `Chart.yaml` as well as in the `CHANGELOG.md` file

**Comment by tobias-trabelsi-sonarsource** [comment]
and a rebase please :see_no_evil: sorry was not aware that your branch was outdated

**Comment by snorlaX-sleeps** [comment]
@tobias-trabelsi-sonarsource done (didn't see the PR for the version change)

**Comment by tobias-trabelsi-sonarsource** [comment]
Thanks for that :+1: I am missing the change in the `Chart.yaml` artifacthub annotation. 
Please note that i need to ping my PM before merging changes to the LTS chart

**Comment by snorlaX-sleeps** [comment]
Apologies, haven't needed to do that in a Helm Chart before - makes sense though

**Comment by snorlaX-sleeps** [comment]
@tobias-trabelsi-sonarsource note that the `latest` chart does env properties for that container very differently, but I am guessing thats because it's a newer version?
https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/deployment.yaml#L130-L139

**Comment by tobias-trabelsi-sonarsource** [comment]
yeah the init container in the LTS chart can not really handle the proxy env vars so thy are not present here. the way you did it is okay for the LTS chart

**Review by tobias-trabelsi-sonarsource — APPROVED** [review]
LGTM :+1: 
again: the merge will have to wait until my PM agrees to this as well

**Comment by tobias-trabelsi-sonarsource** [comment]
Thanks for your contribution. I have merged this but the release will have to wait for the next LTS application update

**Comment by aRobinson-R7** [comment]
Thanks @tobias-trabelsi-sonarsource!

**Pull request merged**
