### PR TITLE
Add revisionHistoryLimit configuration

### PR DESCRIPTION
**Pull request by geomcquat**
Use default [cleanup policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy) but add the possibility to override it for Deployments

### CODE REVIEW

**Comment by stanislavhh** [comment]
Hello @geomcquat, thank you for the contribution, it is being assessed by the team.

**Comment by jCOTINEAU** [comment]
Hello @geomcquat, sorry for the delayed answer.

Thanks a lot for taking the time to participate in the community, this is really valuable for us.

Your changes are really great, could you also apply this to :
- StatefulSet on sonarqube chart
- Deployment and statefulset on the sonarqube-dce chart

On top of that could you add an entry to the changelog and chart.yml to specify your changes ?

Thanks again for the valuable contributions.

**Comment by geomcquat** [comment]
> Hello @geomcquat, sorry for the delayed answer.
> 
> Thanks a lot for taking the time to participate in the community, this is really valuable for us.
> 
> Your changes are really great, could you also apply this to :
> 
> * StatefulSet on sonarqube chart
> * Deployment and statefulset on the sonarqube-dce chart
> 
> On top of that could you add an entry to the changelog and chart.yml to specify your changes ?
> 
> Thanks again for the valuable contributions.

Hi @jCOTINEAU, sorry I always forget the other Chart as we don't use the dce one, here it is : https://github.com/SonarSource/helm-chart-sonarqube/pull/378/files/bf5b0f5bbb06bee49398830c2d7db0dac4166ef3..HEAD

I didn't apply it to StatefulSet as ReplicaSet is only for Deployment type.

**Review by jCOTINEAU — APPROVED** [review]
lgtm. thanks a lot for the huge contribution ! i will merge with a squash commit in order to follow our guidelines

**Pull request merged**
