### PR TITLE
Add ability to specify an optional array of containers to run alongside the `sonarqube` container

### PR DESCRIPTION
**Pull request by dlbock**
# Why

Please see https://github.com/SonarSource/helm-chart-sonarqube/issues/73 for the request and reasoning

# What

- Add an additional configuration parameter `extraContainers` to allow users to specify an array of containers to run alongside the `sonarqube` container either in the `StatefulSet` mode or `Deployment` mode.
- `charts/sonarqube/templates/deployment.yaml` contained duplicate definitions of `nodeSelector`, `tolerations` and `affinity`, therefore removed the duplicates.

### CODE REVIEW

**Comment by joschi** [comment]
```
Checking chart 'sonarqube => (version: "1.0.16", path: "charts/sonarqube")' for a version bump...
Old chart version: 1.0.16
New chart version: 1.0.16
------------------------------------------------------------------------------------------------------------------------
 ✖︎ sonarqube => (version: "1.0.16", path: "charts/sonarqube") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
Error: Error linting charts: Error processing charts
Error linting charts: Error processing charts
```
This looks fixable. 😂 
https://github.com/SonarSource/helm-chart-sonarqube/blob/d02fe50420f66e209d6a43e5148ef8052e5cb337/charts/sonarqube/Chart.yaml#L4

**Comment by wouter-admiraal-sonarsource** [comment]
@tobias-trabelsi-sonarsource I'll assign this one to you 🙂 . Let me know if you need any help.

**Comment by dlbock** [comment]
DOH! It looks like it's been a while since I've updated a helm chart 🤦‍♀️

**Review by tobias-trabelsi-sonarsource — APPROVED** [review]
LGTM, thanks for the contribution :+1:

**Comment by dlbock** [comment]
@tobias-trabelsi-sonarsource I just realized that I didn't add this version `1.0.17` to the Changelog. I might need your help to do that as the PR checks will require the Chart version to be bumped?

**Comment by tobias-trabelsi-sonarsource** [comment]
@dlbock thanks for pointing that out. i will take care of adding this to the changelog :+1:

**Pull request merged**
