### PR TITLE
Remove duplicated parameters from README

### PR DESCRIPTION
**Pull request by wwsean08**
Please ensure your pull request adheres to the following guidelines:
- [X] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [x] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`

Hello,

When setting up my own SonarQube DCE instance I noticed that the `ApplicationNodes.resources` parameters were duplicated in the README.  In addition to where I removed they can also be found at lines 258-261, hence I removed the later section to prevent confusion for more users down the line.

### CODE REVIEW

**Comment by wwsean08** [comment]
rebased with main and fixed merge conflicts

**Review by jCOTINEAU — APPROVED** [review]
lgtm, thanks a lot for your contribution !

**Review by jCOTINEAU — CHANGES_REQUESTED** [review]
LGTM, thanks a lot for your contribution !

in order to be compliant could you just prefix your commit message with NO-JIRA ?

**Comment by wwsean08** [comment]
The commit has been reworded to start with `NO-JIRA`

**Review by jCOTINEAU — APPROVED** [review]
lgtm, thanks a lot for your contribution !

**Pull request merged**
