### PR TITLE
SONAR-20919 Support Kubernetes v1.28 and drop EOL versions

### PR DESCRIPTION
**Pull request by carminevassallo**

### CODE REVIEW

**Comment by davividal** [comment]
```
--- FAIL: TestSonarQubeChartDynamicCompatibility (10259.26s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/standard-chart-default-values-deployment (191.88s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/standard-chart-default-values-sts (192.11s)
    --- FAIL: TestSonarQubeChartDynamicCompatibility/standard-chart-all-values-deployment (4594.98s)
    --- FAIL: TestSonarQubeChartDynamicCompatibility/standard-chart-all-values-sts (4594.92s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/dce-chart-default-values (332.62s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/dce-chart-all-values (352.76s)
FAIL
FAIL	command-line-arguments	10259.632s
FAIL
```

**Comment by carminevassallo** [comment]
Hey @davividal,

do you have more details on why the two tests fail? Given that they took a long time to fail, I suspect that's because there were some imagePull-related errors. Did you import the latest (not yet released) SQ versions when running the tests? I was adding a side note in [SONAR-20919](https://sonarsource.atlassian.net/jira/software/c/projects/SONAR/boards/350?selectedIssue=SONAR-20919) about it...

**Review by davividal — CHANGES_REQUESTED** [review]
The tests are not passing.
Since the tests are using the current image (10.2.1) and the new code, I think it makes sense to fail.

My suggestion:
 ```
diff --git a/tests/dynamic-compatibility-test/sonarqube-dce/all-values.yaml b/tests/dynamic-compatibility-test/sonarqube-dce/all-values.yaml
index eaa747a..4426e2e 100644
--- a/tests/dynamic-compatibility-test/sonarqube-dce/all-values.yaml
+++ b/tests/dynamic-compatibility-test/sonarqube-dce/all-values.yaml
@@ -12,7 +12,7 @@ account:
     requests:
       cpu: 3
       memory: 16Gi
-curlContainerImage: curlimages/curl:8.2.0
+curlContainerImage: curlimages/curl:8.4.0
 adminJobAnnotations:
   someAnnotaion: toto
 sonarWebContext: /
@@ -41,8 +41,9 @@ ingress:
 
 # tests/unit-compatibility-test/sonarqube-dce/install-plugins-values.yaml
 plugins:
- install:
-   - "https://github.com/elegoff/sonar-rust/releases/download/v0.0.9/community-rust-plugin-0.0.9.jar"
+  image: curlimages/curl:8.4.0
+  install:
+  - "https://github.com/elegoff/sonar-rust/releases/download/v0.0.9/community-rust-plugin-0.0.9.jar"
 
 # tests/unit-compatibility-test/sonarqube-dce/jdbc-config-values.yaml # It requires an external db
 # tests/unit-compatibility-test/sonarqube-dce/networkpolicy-values.yaml
diff --git a/tests/dynamic-compatibility-test/sonarqube/all-values.yaml b/tests/dynamic-compatibility-test/sonarqube/all-values.yaml
index 3bc55d0..cd723fe 100644
--- a/tests/dynamic-compatibility-test/sonarqube/all-values.yaml
+++ b/tests/dynamic-compatibility-test/sonarqube/all-values.yaml
@@ -12,7 +12,7 @@ account:
     requests:
       cpu: 3
       memory: 16Gi
-curlContainerImage: curlimages/curl:8.2.0
+curlContainerImage: curlimages/curl:8.4.0
 adminJobAnnotations:
   someAnnotaion: toto
 sonarWebContext: /
@@ -39,8 +39,9 @@ ingress:
 
 # tests/unit-compatibility-test/sonarqube/install-plugins-values.yaml
 plugins:
- install:
-   - "https://github.com/elegoff/sonar-rust/releases/download/v0.0.9/community-rust-plugin-0.0.9.jar"
+  image: curlimages/curl:8.4.0
+  install:
+  - "https://github.com/elegoff/sonar-rust/releases/download/v0.0.9/community-rust-plugin-0.0.9.jar"
 
 # tests/unit-compatibility-test/sonarqube/jdbc-config-values.yaml # It requires an external db
 # tests/unit-compatibility-test/sonarqube/networkpolicy-values.yaml
```

By forcing the images to be curl, the tests will pass. WDYT?

**Comment by davividal** [comment]
> Hey @davividal,
> 
> do you have more details on why the two tests fail? Given that they took a long time to fail, I suspect that's because there were some imagePull-related errors. Did you import the latest (not yet released) SQ versions when running the tests? I was adding a side note in [SONAR-20919](https://sonarsource.atlassian.net/jira/software/c/projects/SONAR/boards/350?selectedIssue=SONAR-20919) about it...

@carminevassallo that's a good point!
I'll import it and it should work then.

**Review by davividal — APPROVED** [review]
```
--- PASS: TestSonarQubeChartDynamicCompatibility (1444.35s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/standard-chart-default-values-deployment (192.09s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/standard-chart-default-values-sts (162.16s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/standard-chart-all-values-deployment (212.50s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/standard-chart-all-values-sts (182.53s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/dce-chart-default-values (332.48s)
    --- PASS: TestSonarQubeChartDynamicCompatibility/dce-chart-all-values (362.59s)
PASS
ok  	command-line-arguments	1445.091s
```

LGTM!

**Pull request merged**
