### PR TITLE
add support ingressClassName

### PR DESCRIPTION
**Pull request by PauloFerreira25**
Please ensure your pull request adheres to the following guidelines:
- [X] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [X] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`
- [X] Bump the Version number of the respected chart

Hello, I'm adding support for the ingressClassName attribute.

This configuration is available for current versions of Ingress.

<https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/#new-features-available-in-kubernetes-118-and-above>

Thank you for your attention

### CODE REVIEW

**Comment by leo-geoffroy-sonarsource** [comment]
Hello @PauloFerreira25 

Thank you for your contribution.
As you can see in [this PR ](https://github.com/SonarSource/helm-chart-sonarqube/pull/202) and also [this one ](https://github.com/SonarSource/helm-chart-sonarqube/pull/79), this change was not ported on the LTS version as we don't consider it as critical or blocker.
Could you explain more why you need this change to be ported and what is the limitation you are currently encountering?

**Comment by PauloFerreira25** [comment]
Hello @leo-geoffroy-sonarsource

Please excuse me if I sound arrogant.

But the lack of this configuration basically prevents using kong as an ingress in place in nginx. This is the reason for my request.

Now, about being LTS. As I understand it, LTS would be for the SonarQube product version, not the chart/helm.

Because, it's very complex that I have to use the "latest version" chart/helm, but have to reconfigure the entire values file to use SonarQube LTS.

I believe they should be treated in different ways, SonarQube product, SonarQube publication.

Thanks again for your attention

**Comment by leo-geoffroy-sonarsource** [comment]
Hello @PauloFerreira25 

I understand your feedback, but SonarQube is a product that is moving fast, so we want to offer a version of the helm chart that will always be compatible with the LTS version of SonarQube and also benefits from critical bugs or security vulnerabilities fixes.

Regarding your issue, and looking at the documentation of Kong, it seems that the annotation "[kubernetes.io/ingress.class](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation)" in replacement of ingressClassName, can you confirm?

**Comment by PauloFerreira25** [comment]
Hello.

This is the official kong documentation:
<https://docs.konghq.com/kubernetes-ingress-controller/2.3.x/references/annotations/#kubernetesioingressclass>

To be honest, I didn't test using ```kubernetes.io/ingress.class```, as yourself showed, this is a Deprecated configuration, for this reason I didn't test it.

I thought it more prudent to make the correction in SonarQube's helm.

To end this thread, I will follow the model of ```kubernetes.io/ingress.class```.

But I sincerely request you to review this LTS policy for the helm/chart.

It is very confusing to lock the publishing process this way.

Mainly, seeing that what I need, and what others open as a request, are included in the "develop":

<https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube>

Again, thanks for your attention.

**Pull request closed without merging**
