### PR TITLE
Issue-139 Fixes and improvements on use of monitoring passcode

### PR DESCRIPTION
**Pull request by kchenye-bitgo**
This PR should address issue #139. Please let me know if I'm missing anything or if there is a better way to handle this.

Changes:

- Add missing passcode from list of environment variables ( sonarqube )
- update livenessProbe to use exec commands and prevent the passcode from being templated in plaintext in the manifest ( sonarqube, sonarqube-dce )

### CODE REVIEW

**Review by tobias-trabelsi-sonarsource — CHANGES_REQUESTED** [review]
Hi @kchenye-bitgo ,

thank you very much for your contribution. could you rebase your branch, increase the chart version number and mention your change in the `Chart.yaml` and the `CHANGELOG.md`?

**Comment by kchenye-bitgo** [comment]
Hi, @tobias-trabelsi-sonarsource,

I've rebased with latest master and updated `Chart.yaml` and `CHANGELOG.md` files as requested.

**Comment by tobias-trabelsi-sonarsource** [comment]
looking good. if you could now just mention your change in the `Chart.yaml` as well so they are displayed on artifacthub this would be ready for merge

**Comment by kchenye-bitgo** [comment]
rebased and updated `Chart.yaml` with the changelog for artifacthub

**Comment by tobias-trabelsi-sonarsource** [comment]
and the chart version needs another bump :confused: 
chart testing is a bit pedantic here but we save all versions of the chart for internal use, so we need to make sure that each change is tracked with the respected chart version

**Comment by kchenye-bitgo** [comment]
bumped once more, also updated `CHANGELOG.md` to list changes under the correct version :smile:

**Review by tobias-trabelsi-sonarsource — APPROVED** [review]
LGTM. Thank you very much :smiley:

**Comment by tobias-trabelsi-sonarsource** [comment]
well... i should have spotted this during the review.. the wget implementation in alpine is not compliant to these changes, so i will revert the change on the probe while keeping the fix on the deployment.

from our production instance: 
```
  Warning  Unhealthy  2m58s (x16 over 20m)  kubelet            Liveness probe failed: BusyBox v1.33.1 () multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header 'HEADER: VALUE'] [-Y on/off]
  [-P DIR] [-U AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

  --spider    Only check URL existence: $? is 0 if exists
  -c            Continue retrieval of aborted transfer
  -q            Quiet
  -P DIR        Save to DIR (default .)
  -S            Show server response
  -T SEC        Network read timeout is SEC seconds
  -O FILE       Save to FILE ('-' for stdout)
  -o LOGFILE  Log messages to FILE
  -U STR        Use STR for User-Agent header
  -Y on/off   Use proxy
```

**Comment by kchenye-bitgo** [comment]
I apologize for this oversight. I suspect this might have been a problem with defining the `wget` arguments as separate items. I believe something in this format should work instead as I have it running for our server:

```
exec:
  command:
    - bash
    - '-c'
    - | 
      wget -qO- \
      --header="X-Sonar-Passcode:${SONAR_WEB_SYSTEMPASSCODE}" \
      http://localhost:9000/api/system/liveness
```

Let me know your thoughts or if you prefer to keep things as is. Cheers!

**Pull request merged**
