### PR TITLE
Add caCerts.enabled flag to Helm chart and README

### PR DESCRIPTION
**Pull request by jgallucci32**
The value `caCerts.enabled` is not specified in the helm chart. The Helm chart only looks for the existence of any value of `caCerts` being defined, such as `caCerts.secrets`. ~~This PR removes the unused field from the README example.~~

UPDATE: PR adds the flag properly to the Helm chart

### CODE REVIEW

**Review by tobias-trabelsi-sonarsource — CHANGES_REQUESTED** [review]
I understand that this is confusing. may i propose instead of just deleting these lines, you mention this in the other values reference in the `README.md` and delete `caCerts.enabled`?

**Comment by jgallucci32** [comment]
@tobias-trabelsi-sonarsource I do not mind going the other direction, however, if we go that way we should add the `caCerts.enabled` flag to the Helm chart rather than just use any value. This would make it more consistent with other parts of the chart.

**Comment by tobias-trabelsi-sonarsource** [comment]
Which makes a lot of sense, but in that case you will need to bump the chart version and mention this change in the `Chart.yaml` as well as in the `CHANGELOG.md` file

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @jgallucci32. I will close this PR due to inactivity while also implementing the suggested logic with #151

**Comment by jgallucci32** [comment]
Sounds good, glad I was able to help in some way.

**Pull request closed without merging**
