### PR TITLE
Add SONAR_WEB_CONTEXT example in comments

### PR DESCRIPTION
**Pull request by SoftwareApe**
Without setting SONAR_WEB_CONTEXT, using a non-default path doesn't work.

This fixes https://github.com/SonarSource/helm-chart-sonarqube/issues/205

Please ensure your pull request adheres to the following guidelines:
- [x] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`
- [ ] Bump the Version number of the respected chart

This is not a change in the chart itself, but in the example config.

### CODE REVIEW

**Comment by leo-geoffroy-sonarsource** [comment]
Hello @SoftwareApe 
Thank you for your contribution.
Could you please also add it to the sonarqube-dce chart, and bump the chart version for both?

**Comment by SoftwareApe** [comment]
Hi @leo-geoffroy-sonarsource, what is dce? Can you take over?

**Comment by SoftwareApe** [comment]
Thank you!

**Comment by SoftwareApe** [comment]
@leo-geoffroy-sonarsource the test says the version need to be bumped? Maybe something else was merged in between?

**Comment by leo-geoffroy-sonarsource** [comment]
> @leo-geoffroy-sonarsource the test says the version need to be bumped? Maybe something else was merged in between?

Indeed, I forgot to change it in Chart.yml, I just pushed the fix

**Comment by leo-geoffroy-sonarsource** [comment]
LGTM with the fix, thanks again for the contribution!

**Pull request merged**
