### PR TITLE
feat(networkpolicies): use the prometheusNamespace value

### PR DESCRIPTION
**Pull request by Mikaciu**
For the prometheusExporter namespace selector, use the `networkPolicy.prometheusNamespace` value instead of using a fixed value.

Please ensure your pull request adheres to the following guidelines:
- [x] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [x] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`
- [x] Bump the Version number of the respected chart

### CODE REVIEW

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @carminevassallo, could you have a look at this PR?

**Comment by leo-geoffroy-sonarsource** [comment]
> > Hi @carminevassallo, could you have a look at this PR?
> 
> Hi @leo-geoffroy-sonarsource,
> 
> I was checking this but we also already discussed already. I think that @Mikaciu's contribution is really valuable because currently we do not use `networkPolicy.prometheusNamespace` parameter in any of our templates and this is a clear bug (we have this parameter mentioned in the README.md). Personally, I'm fine with accepting this contribution, I do not see side effects. This actually will align our sonarqube chart with the dce one. What do you think?

Indeed I think this is a good fix.
@Mikaciu  Could you please update the changelog and chart version to 5.3.0 ? Thanks!

**Comment by Mikaciu** [comment]
> @Mikaciu Could you please update the changelog and chart version to 5.3.0 ? Thanks!

Done, could you please check again ?

**Review by carminevassallo — APPROVED** [review]
LGTM :) @Mikaciu, feel free to merge it when ready.

**Comment by Mikaciu** [comment]
> LGTM :) @Mikaciu, feel free to merge it when ready.

Hello, thanks !

Unfortunately I cant, there's a status message `Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.`

BR

**Comment by carminevassallo** [comment]
> > LGTM :) @Mikaciu, feel free to merge it when ready.
> 
> Hello, thanks !
> 
> Unfortunately I cant, there's a status message `Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.`
> 
> BR

Dear @Mikaciu,

you're right, sorry for the confusion! I'll merge it and thanks for your contribution :)

**Pull request merged**
